# Generated by Django 6.0.1 on 2026-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('11', 'iPhone 11'), ('11 Pro', 'iPhone 11 Pro'), ('11 Pro Max', 'iPhone 11 Pro Max'), ('12 Mini', 'iPhone 12 Mini'), ('12', 'iPhone 12'), ('12 Pro', 'iPhone 12 Pro'), ('12 Pro Max', 'iPhone 12 Pro Max'), ('13 Mini', 'iPhone 13 Mini'), ('13', 'iPhone 13'), ('13 Pro', 'iPhone 13 Pro'), ('13 Pro Max', 'iPhone 13 Pro Max'), ('14', 'iPhone 14'), ('14 Plus', 'iPhone 14 Plus'), ('14 Pro', 'iPhone 14 Pro'), ('14 Pro Max', 'iPhone 14 Pro Max'), ('15', 'iPhone 15'), ('15 Plus', 'iPhone 15 Plus'), ('15 Pro', 'iPhone 15 Pro'), ('15 Pro Max', 'iPhone 15 Pro Max'), ('16', 'iPhone 16'), ('16 Plus', 'iPhone 16 Plus'), ('16 Pro', 'iPhone 16 Pro'), ('16 Pro Max', 'iPhone 16 Pro Max'), ('17', 'iPhone 17'), ('17 Pro', 'iPhone 17 Pro'), ('17 Pro Max', 'iPhone 17 Pro Max')], max_length=50)),
                ('memory', models.CharField(choices=[('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB'), ('512', '512 GB'), ('1024', '1 TB')], max_length=10)),
                ('battery_health', models.IntegerField(default=100)),
                ('condition', models.CharField(choices=[('ideal', 'Ideal'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('has_box', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/')),
                ('is_approved', models.BooleanField(default=True)),
                ('seller_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
